name: Daily Sign-in

on:
  schedule:
    # 每天早上6点运行（UTC时间）
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  daily-signin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests lxml

      - name: Run sign-in script
        env:
          FORUM_COOKIE: ${{ secrets.FORUM_COOKIE }}
        run: python scripts/signin_with_cookie.py
